<?php

/**
 * @file
 * Provides the option to create and manage a set of groups in CiviCRM based on
 * specified Drupal vocabularies.
 */

/**
 * Implements hook_menu().
 */
function civicrm_taxonomy_menu() {
  $items = array();

  $items['admin/config/civicrm-taxonomy'] = array(
    'title' => 'CiviCRM Taxonomy Groups settings',
    'description' => 'Administration settings for the CiviCRM Taxonomy Groups module',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('civicrm_taxonomy_settings_form'),
    'access arguments' => array('administer civicrm taxonomy groups'),
    'file' => 'includes/civicrm_taxonomy.admin.inc',
  );

  return $items;
}

/**
 * Implements hook_permission().
 */
function civicrm_taxonomy_permission() {
  return array(
    'administer civicrm taxonomy groups' => array(
      'title' => t('Administer CiviCRM Taxonomy Groups'),
      'description' => t('Perform administration tasks for the CiviCRM Taxonomy Groups module.'),
    ),
  );
}

/**
 * Implements hook_taxonomy_term_insert().
 */
function civicrm_taxonomy_taxonomy_term_insert($term) {
  $settings = civicrm_taxonomy_status($term->vid);
  if ($settings['status'] == 1) {
    module_load_include('inc', 'civicrm_taxonomy', 'includes/core');

    // Create a new group in CiviCRM.
    civicrm_taxonomy_link_write($term, $settings['option_groups']);
  }
}

/**
 * Implements hook_taxonomy_term_update().
 */
function civicrm_taxonomy_taxonomy_term_update($term) {
  $status = civicrm_taxonomy_status($term->vid);
  if ($status['status'] == 1) {
    module_load_include('inc', 'civicrm_taxonomy', 'includes/core');
    
    // Create a new group in CiviCRM.    
    civicrm_taxonomy_link_write($term, $status['option_groups']);
  }
}

/**
 * Implements hook_taxonomy_term_delete().
 */
function civicrm_taxonomy_taxonomy_term_delete($term) {
  $status = civicrm_taxonomy_status($term->vid); 
  if ($status['status']) {
    module_load_include('inc', 'civicrm_taxonomy', 'includes/core');

    // Delete the group from CiviCRM.
    // TODO: Replace the TRUE value with an admin setting specific for that
    // vocabulary.
    civicrm_taxonomy_link_delete($term->vid, $term->tid, TRUE, $status['option_groups']);
  }
}

/**
 * Checks to see if a taxonomy vocabulary should be mirrored with CiviCRM.
 */
function civicrm_taxonomy_status($vid) {
  $settings = variable_get('civicrm_taxonomy_settings');
  return $settings ? array('status' => $settings['vocabularies'][$vid], 'option_groups' => $settings['advanced']['option_groups']) : NULL;
}
